<Project>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
    <ScpslManaged Condition="'$(ScpslManaged)' == ''">C:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed</ScpslManaged>
    <ExiledRefs Condition="'$(ExiledRefs)' == ''">$(MSBuildThisFileDirectory)..\.tools\exiled\SCP Secret Laboratory\LabAPI\dependencies\global</ExiledRefs>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\*.cs" Link="Shared\%(Filename)%(Extension)" />
    <Reference Include="LabApi"><HintPath>$(ScpslManaged)\LabApi.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(ScpslManaged)\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp-firstpass"><HintPath>$(ScpslManaged)\Assembly-CSharp-firstpass.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="CommandSystem.Core"><HintPath>$(ScpslManaged)\CommandSystem.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="NorthwoodLib"><HintPath>$(ScpslManaged)\NorthwoodLib.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mirror"><HintPath>$(ScpslManaged)\Mirror.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(ScpslManaged)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(ScpslManaged)\UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(ScpslManaged)\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
</Project>
